### ISSUE TITLE
Possibility of an example backend server?

### ISSUE THREAD

**Issue by TryTryAgain** [MacroPower/macropower-analytics-panel#2]
This is a great idea and project, thanks for sharing. Are there any plans to offer an example backend to help adoption and time to configure? I'd love to use this but I'm way too novice to take the time to figure that out at the moment.

**Comment by MacroPower** [comment]
Hello sir, thanks for checking out the plugin.

If you don't have time to set something custom up, the submitter of #1 is using Telegraf, which seems like a great idea to me. You do lose some functionality (you'll need to disable "post end" in the options), but it is very simple to set up and maintain!

To reiterate what I posted in #1, I have added an example Telegraf config in a new "example" directory, click [here](https://github.com/MacroPower/macropower-analytics-panel/blob/master/example/telegraf.conf). Please feel free to play around with the options. I have the output set to file, just so it's a bit easier to test:

![image](https://user-images.githubusercontent.com/5648814/84200406-bbafa480-aa74-11ea-9b3e-2015a74cc159.png)

I also added a new option in the plugin's settings to disable cors, if you require that for testing.

**Comment by TryTryAgain** [comment]
Thanks for the direction/tips and explanation.

**Comment by MacroPower** [comment]
No problem. I will close this issue now. If you run into any other problems or have any other questions, please feel free to open a new issue!
