### ISSUE TITLE
Are there any instructions on how to configure this plugin on grafana.net please?

### ISSUE THREAD

**Issue by PreetSangha** [MacroPower/macropower-analytics-panel#31]
Hi @MacroPower 

I'm using the hosted grafana.net service. I was able to install the plugin on grafana.com and it shows up as installed

### on grafana.com
![image](https://user-images.githubusercontent.com/15098094/155908784-b00af024-8d2f-42a6-a270-84005905e3f5.png)

### on grafana.net 
![image](https://user-images.githubusercontent.com/15098094/155908933-0eec6047-da17-4710-941b-67062a272033.png)

And I've seen the [jtommi](https://github.com/jtommi/analytics-panel-listener) notes on how to create a server to capture the statistics it will fire...

So I create a folder and a dashboard:

![image](https://user-images.githubusercontent.com/15098094/155909171-b3913256-e849-47ba-90d3-aef432f6ee1d.png)

I see nothing in panels

![image](https://user-images.githubusercontent.com/15098094/155909206-ad486a63-b08a-427c-af66-2418c3cf4999.png)

So my questions are:

1. How to configure this panel (I cannot find any instructions on how to plug the server URL in)
2. How to add the panel to a dashboard.

**Comment by MacroPower** [comment]
In order to configure the panel, you have to add it to a dashboard first.

https://grafana.com/docs/grafana/next/panels/working-with-panels/add-panel/

It should appear in the list of available panels (step 6).
