### ISSUE TITLE
Grafana Dashboard Tracking

### ISSUE THREAD

**Issue by joshianant34** [MacroPower/macropower-analytics-panel#32]
@MacroPower  Can I use this plugin to find out the count of users coming onto a particular grafana dashboard , if yes then pls guide how to extract that data?

**Comment by MacroPower** [comment]
If you're using the included server,
```
count by (user_name, dashboard_name) (increase(grafana_analytics_sessions_total[1h]))
```
or similar queries should work.

**Comment by nischalat** [comment]
Hi, I have the same problem. I'm trying to get the # of views for the current dashboard and have the following questions

- What data source would I perform the above query on? I suspect I do not see the relevant one
- Do we need to setup an endpoint to be able to perform this query?
- Is there any documentation on how to write these queries? coz I'm also looking to capture the user info & time details

**Comment by MacroPower** [comment]
In my example I've given a Prometheus query: https://prometheus.io/ But you could use anything that supports OpenMetrics and/or your logging system of choice. Please see the readme and [macropower-analytics-panel/server](https://github.com/MacroPower/macropower-analytics-panel/tree/master/server) for details and documentation.
